---
- name: Install nginx and set up webpage
  hosts: webservers
  remote_user: bohdan
  become: true

  roles: 
    - webserver

# - name: Configure bind9 and add AAAA record of nginx webserver
#   hosts: dns_servers
#   remote_user: bohdan

#   roles: 
#     - dns

# - name: Connect machine to dns, and get webpage by dns-name
#   hosts: users
#   remote_user: bohdan

#   roles: 
#     - user

