---
- name: Install nginx and set up webpage
  hosts: webservers
  remote_user: ubuntu
  become: true

  roles: 
    - webserver

- name: Configure bind9, add AAAA record of webserver
  hosts: dns_servers
  remote_user: ubuntu
  become: true

  roles: 
    - dns

- name: Connect machine to dns, and get webpage by dns-name
  hosts: users
  remote_user: ubuntu
  become: true

  roles: 
    - user

