---
- name: Install bind9
  apt:
    name: bind9

- name: Change bind9 configuration
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    backup: yes
  
- name: Force bind9 to work only with ipv4
  lineinfile: 
    path: /etc/default/named
    line: OPTIONS="-4 -u bind"
    
- name: Enable firewall and allow ssh
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH

- name: Allow firewall to use bind9
  ufw: 
    rule: allow 
    name: Bind9

