---
- name: Update repositories and install bind9
  apt:
    name: bind9
    update_cache: yes

- name: Change bind9 configuration
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    backup: yes
  
- name: Force bind9 to work only with ipv4
  lineinfile: 
    path: /etc/default/named
    line: OPTIONS="-4 -u bind"
    
- name: Make sure ufw is active
  systemd: 
    name: ufw
    state: started

- name: Allow firewall to use bind9
  ufw:
    rule: allow
    name: bind9

